import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Results from '../components/Results';
import Thumbnail from '../components/Thumbnail';
import requests from '../utils/requests';
const API_KEY = process.env.API_KEY;
console.log('api', API_KEY);
export default function Home({ results }) {
  console.log('props', results);
  return (
    <div>
      <Head>
        <title>Mochi Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Thumbnail results={results} /> */}
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps() {
  // const API_KEY = process.env.RAWG_API_KEY;
  const request = await fetch(
    `https://api.rawg.io/api/games?key=${API_KEY}`
  ).then((res) => res.json());
  console.log(request);

  return {
    props: {
      results: request.results || null,
    },
  };
}
