import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import { signIn, signOut, useSession } from 'next-auth/react'
import Link from 'next/link'



export default function Home() {
  // const {data: session, status} = useSession()
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Mochi Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link passHref href="/auth/login/signin">
            <a>
              <h2>Signin</h2>
              <p>Visit custom sign-in page</p>
            </a>
      </Link>
    </div>
    </>
  );
}
